//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoRentalService.AppDBank {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppDBank.ICreditCardService")]
    public interface ICreditCardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/Authorise", ReplyAction="http://tempuri.org/ICreditCardService/AuthoriseResponse")]
        string Authorise(string creditcard, string expiry, string cvv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/Credit", ReplyAction="http://tempuri.org/ICreditCardService/CreditResponse")]
        int Credit(string creditcard, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/Debit", ReplyAction="http://tempuri.org/ICreditCardService/DebitResponse")]
        int Debit(string creditcard, double amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditCardServiceChannel : VideoRentalService.AppDBank.ICreditCardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditCardServiceClient : System.ServiceModel.ClientBase<VideoRentalService.AppDBank.ICreditCardService>, VideoRentalService.AppDBank.ICreditCardService {
        
        public CreditCardServiceClient() {
        }
        
        public CreditCardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditCardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Authorise(string creditcard, string expiry, string cvv) {
            return base.Channel.Authorise(creditcard, expiry, cvv);
        }
        
        public int Credit(string creditcard, double amount) {
            return base.Channel.Credit(creditcard, amount);
        }
        
        public int Debit(string creditcard, double amount) {
            return base.Channel.Debit(creditcard, amount);
        }
    }
}
