//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHarness.RefundServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RefundServiceRef.IRefundService")]
    public interface IRefundService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefundService/RefundPayment", ReplyAction="http://tempuri.org/IRefundService/RefundPaymentResponse")]
        string RefundPayment(int paymentid, int customer_id, int staff_id, int rental_id, decimal amount, System.DateTime paymentDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefundService/GetStaffID", ReplyAction="http://tempuri.org/IRefundService/GetStaffIDResponse")]
        int GetStaffID(string loginName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRefundServiceChannel : ServiceHarness.RefundServiceRef.IRefundService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RefundServiceClient : System.ServiceModel.ClientBase<ServiceHarness.RefundServiceRef.IRefundService>, ServiceHarness.RefundServiceRef.IRefundService {
        
        public RefundServiceClient() {
        }
        
        public RefundServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RefundServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RefundServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RefundServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RefundPayment(int paymentid, int customer_id, int staff_id, int rental_id, decimal amount, System.DateTime paymentDate) {
            return base.Channel.RefundPayment(paymentid, customer_id, staff_id, rental_id, amount, paymentDate);
        }
        
        public int GetStaffID(string loginName) {
            return base.Channel.GetStaffID(loginName);
        }
    }
}
