//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiColumnList.RentalService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SCustomer", Namespace="http://schemas.datacontract.org/2004/07/VideoRentalService")]
    [System.SerializableAttribute()]
    public partial class SCustomer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int address_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime create_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int customer_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string first_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte store_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int address_id {
            get {
                return this.address_idField;
            }
            set {
                if ((this.address_idField.Equals(value) != true)) {
                    this.address_idField = value;
                    this.RaisePropertyChanged("address_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime create_date {
            get {
                return this.create_dateField;
            }
            set {
                if ((this.create_dateField.Equals(value) != true)) {
                    this.create_dateField = value;
                    this.RaisePropertyChanged("create_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int customer_id {
            get {
                return this.customer_idField;
            }
            set {
                if ((this.customer_idField.Equals(value) != true)) {
                    this.customer_idField = value;
                    this.RaisePropertyChanged("customer_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.first_nameField, value) != true)) {
                    this.first_nameField = value;
                    this.RaisePropertyChanged("first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.last_nameField, value) != true)) {
                    this.last_nameField = value;
                    this.RaisePropertyChanged("last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte store_id {
            get {
                return this.store_idField;
            }
            set {
                if ((this.store_idField.Equals(value) != true)) {
                    this.store_idField = value;
                    this.RaisePropertyChanged("store_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SRental", Namespace="http://schemas.datacontract.org/2004/07/VideoRentalService")]
    [System.SerializableAttribute()]
    public partial class SRental : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilmtitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int customer_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int inventory_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime rental_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rental_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> return_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte staff_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filmtitle {
            get {
                return this.FilmtitleField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmtitleField, value) != true)) {
                    this.FilmtitleField = value;
                    this.RaisePropertyChanged("Filmtitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int customer_id {
            get {
                return this.customer_idField;
            }
            set {
                if ((this.customer_idField.Equals(value) != true)) {
                    this.customer_idField = value;
                    this.RaisePropertyChanged("customer_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int inventory_id {
            get {
                return this.inventory_idField;
            }
            set {
                if ((this.inventory_idField.Equals(value) != true)) {
                    this.inventory_idField = value;
                    this.RaisePropertyChanged("inventory_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime rental_date {
            get {
                return this.rental_dateField;
            }
            set {
                if ((this.rental_dateField.Equals(value) != true)) {
                    this.rental_dateField = value;
                    this.RaisePropertyChanged("rental_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rental_id {
            get {
                return this.rental_idField;
            }
            set {
                if ((this.rental_idField.Equals(value) != true)) {
                    this.rental_idField = value;
                    this.RaisePropertyChanged("rental_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> return_date {
            get {
                return this.return_dateField;
            }
            set {
                if ((this.return_dateField.Equals(value) != true)) {
                    this.return_dateField = value;
                    this.RaisePropertyChanged("return_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte staff_id {
            get {
                return this.staff_idField;
            }
            set {
                if ((this.staff_idField.Equals(value) != true)) {
                    this.staff_idField = value;
                    this.RaisePropertyChanged("staff_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SPayment", Namespace="http://schemas.datacontract.org/2004/07/VideoRentalService")]
    [System.SerializableAttribute()]
    public partial class SPayment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int customer_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string filmtitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int inventory_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime payment_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int payment_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> rental_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte staff_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int customer_id {
            get {
                return this.customer_idField;
            }
            set {
                if ((this.customer_idField.Equals(value) != true)) {
                    this.customer_idField = value;
                    this.RaisePropertyChanged("customer_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filmtitle {
            get {
                return this.filmtitleField;
            }
            set {
                if ((object.ReferenceEquals(this.filmtitleField, value) != true)) {
                    this.filmtitleField = value;
                    this.RaisePropertyChanged("filmtitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int inventory_id {
            get {
                return this.inventory_idField;
            }
            set {
                if ((this.inventory_idField.Equals(value) != true)) {
                    this.inventory_idField = value;
                    this.RaisePropertyChanged("inventory_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime payment_date {
            get {
                return this.payment_dateField;
            }
            set {
                if ((this.payment_dateField.Equals(value) != true)) {
                    this.payment_dateField = value;
                    this.RaisePropertyChanged("payment_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int payment_id {
            get {
                return this.payment_idField;
            }
            set {
                if ((this.payment_idField.Equals(value) != true)) {
                    this.payment_idField = value;
                    this.RaisePropertyChanged("payment_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> rental_id {
            get {
                return this.rental_idField;
            }
            set {
                if ((this.rental_idField.Equals(value) != true)) {
                    this.rental_idField = value;
                    this.RaisePropertyChanged("rental_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte staff_id {
            get {
                return this.staff_idField;
            }
            set {
                if ((this.staff_idField.Equals(value) != true)) {
                    this.staff_idField = value;
                    this.RaisePropertyChanged("staff_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategorySale", Namespace="http://schemas.datacontract.org/2004/07/VideoRentalService")]
    [System.SerializableAttribute()]
    public partial class CategorySale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> total_salesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> total_sales {
            get {
                return this.total_salesField;
            }
            set {
                if ((this.total_salesField.Equals(value) != true)) {
                    this.total_salesField = value;
                    this.RaisePropertyChanged("total_sales");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentalService.IRentalService")]
    public interface IRentalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/HireMovie", ReplyAction="http://tempuri.org/IRentalService/HireMovieResponse")]
        int HireMovie(int staffid, int customerid, int rentalid, double paymentAmount, string creditcardno, string expiry, string cvv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/HireMovie", ReplyAction="http://tempuri.org/IRentalService/HireMovieResponse")]
        System.Threading.Tasks.Task<int> HireMovieAsync(int staffid, int customerid, int rentalid, double paymentAmount, string creditcardno, string expiry, string cvv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/Refund", ReplyAction="http://tempuri.org/IRentalService/RefundResponse")]
        int Refund(int staffid, int customerid, double paymentAmount, string creditcardno, string expiry, string cvv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/Refund", ReplyAction="http://tempuri.org/IRentalService/RefundResponse")]
        System.Threading.Tasks.Task<int> RefundAsync(int staffid, int customerid, double paymentAmount, string creditcardno, string expiry, string cvv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/RefundT", ReplyAction="http://tempuri.org/IRentalService/RefundTResponse")]
        int RefundT(int staffid, int customerid, double paymentAmount, string creditcardno, string expiry, string cvv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/RefundT", ReplyAction="http://tempuri.org/IRentalService/RefundTResponse")]
        System.Threading.Tasks.Task<int> RefundTAsync(int staffid, int customerid, double paymentAmount, string creditcardno, string expiry, string cvv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetCustomersByText", ReplyAction="http://tempuri.org/IRentalService/GetCustomersByTextResponse")]
        MultiColumnList.RentalService.SCustomer[] GetCustomersByText(string searchtext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetCustomersByText", ReplyAction="http://tempuri.org/IRentalService/GetCustomersByTextResponse")]
        System.Threading.Tasks.Task<MultiColumnList.RentalService.SCustomer[]> GetCustomersByTextAsync(string searchtext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetCustomer", ReplyAction="http://tempuri.org/IRentalService/GetCustomerResponse")]
        MultiColumnList.RentalService.SCustomer GetCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetCustomer", ReplyAction="http://tempuri.org/IRentalService/GetCustomerResponse")]
        System.Threading.Tasks.Task<MultiColumnList.RentalService.SCustomer> GetCustomerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetCustomers", ReplyAction="http://tempuri.org/IRentalService/GetCustomersResponse")]
        MultiColumnList.RentalService.SCustomer[] GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetCustomers", ReplyAction="http://tempuri.org/IRentalService/GetCustomersResponse")]
        System.Threading.Tasks.Task<MultiColumnList.RentalService.SCustomer[]> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetRentals", ReplyAction="http://tempuri.org/IRentalService/GetRentalsResponse")]
        MultiColumnList.RentalService.SRental[] GetRentals(int customerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetRentals", ReplyAction="http://tempuri.org/IRentalService/GetRentalsResponse")]
        System.Threading.Tasks.Task<MultiColumnList.RentalService.SRental[]> GetRentalsAsync(int customerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetPayments", ReplyAction="http://tempuri.org/IRentalService/GetPaymentsResponse")]
        MultiColumnList.RentalService.SPayment[] GetPayments(int customerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetPayments", ReplyAction="http://tempuri.org/IRentalService/GetPaymentsResponse")]
        System.Threading.Tasks.Task<MultiColumnList.RentalService.SPayment[]> GetPaymentsAsync(int customerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetPaymentsByRental", ReplyAction="http://tempuri.org/IRentalService/GetPaymentsByRentalResponse")]
        MultiColumnList.RentalService.SPayment[] GetPaymentsByRental(int rentalid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetPaymentsByRental", ReplyAction="http://tempuri.org/IRentalService/GetPaymentsByRentalResponse")]
        System.Threading.Tasks.Task<MultiColumnList.RentalService.SPayment[]> GetPaymentsByRentalAsync(int rentalid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetRentalByPayment", ReplyAction="http://tempuri.org/IRentalService/GetRentalByPaymentResponse")]
        MultiColumnList.RentalService.SRental GetRentalByPayment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetRentalByPayment", ReplyAction="http://tempuri.org/IRentalService/GetRentalByPaymentResponse")]
        System.Threading.Tasks.Task<MultiColumnList.RentalService.SRental> GetRentalByPaymentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetPayment", ReplyAction="http://tempuri.org/IRentalService/GetPaymentResponse")]
        MultiColumnList.RentalService.SPayment GetPayment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetPayment", ReplyAction="http://tempuri.org/IRentalService/GetPaymentResponse")]
        System.Threading.Tasks.Task<MultiColumnList.RentalService.SPayment> GetPaymentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetSalesByCategory", ReplyAction="http://tempuri.org/IRentalService/GetSalesByCategoryResponse")]
        MultiColumnList.RentalService.CategorySale[] GetSalesByCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetSalesByCategory", ReplyAction="http://tempuri.org/IRentalService/GetSalesByCategoryResponse")]
        System.Threading.Tasks.Task<MultiColumnList.RentalService.CategorySale[]> GetSalesByCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetRewardsReport", ReplyAction="http://tempuri.org/IRentalService/GetRewardsReportResponse")]
        MultiColumnList.RentalService.SCustomer[] GetRewardsReport(System.Nullable<sbyte> min_monthly_purchases, System.Nullable<decimal> min_dollar_amount_purchased, int count_rewardees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/GetRewardsReport", ReplyAction="http://tempuri.org/IRentalService/GetRewardsReportResponse")]
        System.Threading.Tasks.Task<MultiColumnList.RentalService.SCustomer[]> GetRewardsReportAsync(System.Nullable<sbyte> min_monthly_purchases, System.Nullable<decimal> min_dollar_amount_purchased, int count_rewardees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/Logon", ReplyAction="http://tempuri.org/IRentalService/LogonResponse")]
        MultiColumnList.RentalService.LogonResponse Logon(MultiColumnList.RentalService.LogonRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/Logon", ReplyAction="http://tempuri.org/IRentalService/LogonResponse")]
        System.Threading.Tasks.Task<MultiColumnList.RentalService.LogonResponse> LogonAsync(MultiColumnList.RentalService.LogonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/ServiceCheck", ReplyAction="http://tempuri.org/IRentalService/ServiceCheckResponse")]
        int ServiceCheck();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/ServiceCheck", ReplyAction="http://tempuri.org/IRentalService/ServiceCheckResponse")]
        System.Threading.Tasks.Task<int> ServiceCheckAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/RefundPayment", ReplyAction="http://tempuri.org/IRentalService/RefundPaymentResponse")]
        bool RefundPayment(int paymentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/RefundPayment", ReplyAction="http://tempuri.org/IRentalService/RefundPaymentResponse")]
        System.Threading.Tasks.Task<bool> RefundPaymentAsync(int paymentid);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logon", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int userID;
        
        public LogonRequest() {
        }
        
        public LogonRequest(string user, string password, int userID) {
            this.user = user;
            this.password = password;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogonResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool LogonResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userID;
        
        public LogonResponse() {
        }
        
        public LogonResponse(bool LogonResult, int userID) {
            this.LogonResult = LogonResult;
            this.userID = userID;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRentalServiceChannel : MultiColumnList.RentalService.IRentalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentalServiceClient : System.ServiceModel.ClientBase<MultiColumnList.RentalService.IRentalService>, MultiColumnList.RentalService.IRentalService {
        
        public RentalServiceClient() {
        }
        
        public RentalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int HireMovie(int staffid, int customerid, int rentalid, double paymentAmount, string creditcardno, string expiry, string cvv) {
            return base.Channel.HireMovie(staffid, customerid, rentalid, paymentAmount, creditcardno, expiry, cvv);
        }
        
        public System.Threading.Tasks.Task<int> HireMovieAsync(int staffid, int customerid, int rentalid, double paymentAmount, string creditcardno, string expiry, string cvv) {
            return base.Channel.HireMovieAsync(staffid, customerid, rentalid, paymentAmount, creditcardno, expiry, cvv);
        }
        
        public int Refund(int staffid, int customerid, double paymentAmount, string creditcardno, string expiry, string cvv) {
            return base.Channel.Refund(staffid, customerid, paymentAmount, creditcardno, expiry, cvv);
        }
        
        public System.Threading.Tasks.Task<int> RefundAsync(int staffid, int customerid, double paymentAmount, string creditcardno, string expiry, string cvv) {
            return base.Channel.RefundAsync(staffid, customerid, paymentAmount, creditcardno, expiry, cvv);
        }
        
        public int RefundT(int staffid, int customerid, double paymentAmount, string creditcardno, string expiry, string cvv) {
            return base.Channel.RefundT(staffid, customerid, paymentAmount, creditcardno, expiry, cvv);
        }
        
        public System.Threading.Tasks.Task<int> RefundTAsync(int staffid, int customerid, double paymentAmount, string creditcardno, string expiry, string cvv) {
            return base.Channel.RefundTAsync(staffid, customerid, paymentAmount, creditcardno, expiry, cvv);
        }
        
        public MultiColumnList.RentalService.SCustomer[] GetCustomersByText(string searchtext) {
            return base.Channel.GetCustomersByText(searchtext);
        }
        
        public System.Threading.Tasks.Task<MultiColumnList.RentalService.SCustomer[]> GetCustomersByTextAsync(string searchtext) {
            return base.Channel.GetCustomersByTextAsync(searchtext);
        }
        
        public MultiColumnList.RentalService.SCustomer GetCustomer(int id) {
            return base.Channel.GetCustomer(id);
        }
        
        public System.Threading.Tasks.Task<MultiColumnList.RentalService.SCustomer> GetCustomerAsync(int id) {
            return base.Channel.GetCustomerAsync(id);
        }
        
        public MultiColumnList.RentalService.SCustomer[] GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<MultiColumnList.RentalService.SCustomer[]> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public MultiColumnList.RentalService.SRental[] GetRentals(int customerid) {
            return base.Channel.GetRentals(customerid);
        }
        
        public System.Threading.Tasks.Task<MultiColumnList.RentalService.SRental[]> GetRentalsAsync(int customerid) {
            return base.Channel.GetRentalsAsync(customerid);
        }
        
        public MultiColumnList.RentalService.SPayment[] GetPayments(int customerid) {
            return base.Channel.GetPayments(customerid);
        }
        
        public System.Threading.Tasks.Task<MultiColumnList.RentalService.SPayment[]> GetPaymentsAsync(int customerid) {
            return base.Channel.GetPaymentsAsync(customerid);
        }
        
        public MultiColumnList.RentalService.SPayment[] GetPaymentsByRental(int rentalid) {
            return base.Channel.GetPaymentsByRental(rentalid);
        }
        
        public System.Threading.Tasks.Task<MultiColumnList.RentalService.SPayment[]> GetPaymentsByRentalAsync(int rentalid) {
            return base.Channel.GetPaymentsByRentalAsync(rentalid);
        }
        
        public MultiColumnList.RentalService.SRental GetRentalByPayment(int id) {
            return base.Channel.GetRentalByPayment(id);
        }
        
        public System.Threading.Tasks.Task<MultiColumnList.RentalService.SRental> GetRentalByPaymentAsync(int id) {
            return base.Channel.GetRentalByPaymentAsync(id);
        }
        
        public MultiColumnList.RentalService.SPayment GetPayment(int id) {
            return base.Channel.GetPayment(id);
        }
        
        public System.Threading.Tasks.Task<MultiColumnList.RentalService.SPayment> GetPaymentAsync(int id) {
            return base.Channel.GetPaymentAsync(id);
        }
        
        public MultiColumnList.RentalService.CategorySale[] GetSalesByCategory() {
            return base.Channel.GetSalesByCategory();
        }
        
        public System.Threading.Tasks.Task<MultiColumnList.RentalService.CategorySale[]> GetSalesByCategoryAsync() {
            return base.Channel.GetSalesByCategoryAsync();
        }
        
        public MultiColumnList.RentalService.SCustomer[] GetRewardsReport(System.Nullable<sbyte> min_monthly_purchases, System.Nullable<decimal> min_dollar_amount_purchased, int count_rewardees) {
            return base.Channel.GetRewardsReport(min_monthly_purchases, min_dollar_amount_purchased, count_rewardees);
        }
        
        public System.Threading.Tasks.Task<MultiColumnList.RentalService.SCustomer[]> GetRewardsReportAsync(System.Nullable<sbyte> min_monthly_purchases, System.Nullable<decimal> min_dollar_amount_purchased, int count_rewardees) {
            return base.Channel.GetRewardsReportAsync(min_monthly_purchases, min_dollar_amount_purchased, count_rewardees);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultiColumnList.RentalService.LogonResponse MultiColumnList.RentalService.IRentalService.Logon(MultiColumnList.RentalService.LogonRequest request) {
            return base.Channel.Logon(request);
        }
        
        public bool Logon(string user, string password, ref int userID) {
            MultiColumnList.RentalService.LogonRequest inValue = new MultiColumnList.RentalService.LogonRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.userID = userID;
            MultiColumnList.RentalService.LogonResponse retVal = ((MultiColumnList.RentalService.IRentalService)(this)).Logon(inValue);
            userID = retVal.userID;
            return retVal.LogonResult;
        }
        
        public System.Threading.Tasks.Task<MultiColumnList.RentalService.LogonResponse> LogonAsync(MultiColumnList.RentalService.LogonRequest request) {
            return base.Channel.LogonAsync(request);
        }
        
        public int ServiceCheck() {
            return base.Channel.ServiceCheck();
        }
        
        public System.Threading.Tasks.Task<int> ServiceCheckAsync() {
            return base.Channel.ServiceCheckAsync();
        }
        
        public bool RefundPayment(int paymentid) {
            return base.Channel.RefundPayment(paymentid);
        }
        
        public System.Threading.Tasks.Task<bool> RefundPaymentAsync(int paymentid) {
            return base.Channel.RefundPaymentAsync(paymentid);
        }
    }
}
